- .circleci/config.yml
Remove StrictHostKeyChecking from .ssh/config
Contributors:
- Tyson Wolker
> fix(circleci):

- package-lock.json
- src/components/Typeahead/__tests__/Typeahead.js
- src/components/Typeahead/index.js
- Add guarantee `fetchListOnInput` only invoked by the user manually updating input value and not polluted by other interactions (e.g. a user clicking a dropdown item and the value automatically populating the input value)
- Expose selectItemCollector to allow component consumers to maintain reference to Downshift's `selectItem` hook
- Remap `onBlur` prop directly to underlying input element
> fix(typeahead)

- package-lock.json
- src/components/ExternalLink/README.md
- src/components/ExternalLink/__tests__/ExternalLink.spec.js
- src/components/ExternalLink/__tests__/__snapshots__/ExternalLink.spec.js.snap
- src/components/ExternalLink/index.js
- src/components/PopupField/__tests__/__snapshots__/PopupField.spec.js.snap
- src/theme/airways.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/22)
> feat(external-links): Implement ExternalLink component design with responsive behaviours

- .circleci/config.yml
- .github/auto_assign.yml
- package-lock.json
Please forgive me :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/25)
> fix(ci): Added linting to ci

- package-lock.json
- src/components/Dropdown/README.md
- src/components/Dropdown/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/31)
> feat(dropdown): Make dropdown full width left align

- package-lock.json
- src/components/ExternalLink/README.md
- src/components/ExternalLink/__tests__/ExternalLink.spec.js
- src/components/ExternalLink/__tests__/__snapshots__/ExternalLink.spec.js.snap
- src/components/ExternalLink/index.js
- src/icons/PinIcon/README.md
- src/utils/classname.js
- styleguide.config.js
- Map font colours to correct media queries
- Implement renderIcon prop/MediaQueryDetector, dynamically hand desired icon fill colour via params, update tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/28)
> fix(externallink): Map font colours to correct media query rules, add better icon colour handling

- package-lock.json
- package.json
- src/components/Calendar/README.md
- src/components/Calendar/__tests__/CalendarHeader.spec.js
- src/components/Calendar/__tests__/__snapshots__/CalendarHeader.spec.js.snap
- src/components/Calendar/components/CalendarHeader.js
- src/components/Calendar/index.js
- src/components/ExternalLink/__tests__/__snapshots__/ExternalLink.spec.js.snap
- src/components/ExternalLink/index.js
- src/components/PopupField/__tests__/__snapshots__/PopupField.spec.js.snap
- src/constants/css.js
- src/icons/Triangle/README.md
- src/icons/Triangle/index.js
- src/shared/ButtonWithDialog/__test__/__snapshots__/Button.spec.js.snap
- src/shared/ButtonWithDialog/__test__/__snapshots__/ButtonWithDialog.spec.js.snap
- src/theme/airways.js
- styleguide.config.js
The new component created for the calendare header and pass props for the functional stateless component.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/37)
> feat(daypicker) : calendar header

- src/components/Dropdown/index.js
- src/components/ExternalLink/__tests__/__snapshots__/ExternalLink.spec.js.snap
- src/components/ExternalLink/index.js
- src/components/PopupField/__tests__/__snapshots__/PopupField.spec.js.snap
- src/components/Toggle/index.js
- src/components/Typeahead/index.js
- src/shared/ButtonWithDialog/__test__/__snapshots__/Button.spec.js.snap
- src/shared/ButtonWithDialog/__test__/__snapshots__/ButtonWithDialog.spec.js.snap
- src/shared/ButtonWithDialog/components/Button.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/38)
> feat : textTransform set to none. previous value: uppercase

- src/components/DayPicker/components/Month.js
- src/components/Dropdown/README.md
- src/components/Dropdown/components/Menu.js
- src/components/Dropdown/components/MenuItem.js
- src/components/Dropdown/index.js
- src/components/Toggle/README.md
- src/components/Toggle/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/42)
> feat(styling): Some minor styling fixes

- src/components/Dropdown/README.md
- src/components/Dropdown/components/MenuItem.js
- src/components/Dropdown/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/43)
> fix(dropdown): some styling fixes

- package-lock.json
- package.json
- rollup.js
- src/theme/airways/colours.json
- src/theme/airways/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/21)
> feat(theme): Refactored colours into a separate JSON file so that we can import that file directly in other projects.

- src/components/DayPicker/README.md
- src/components/DayPicker/__tests__/__snapshots__/Day.spec.js.snap
- src/components/DayPicker/__tests__/__snapshots__/DayPicker.spec.js.snap
- src/components/DayPicker/__tests__/__snapshots__/Header.spec.js.snap
- src/components/DayPicker/components/Day.js
- src/components/DayPicker/components/Header.js
- src/components/DayPicker/components/Price.js
- src/components/DayPicker/helpers/index.js
- src/components/DayPicker/index.js
- src/theme/airways/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/49)
> feat(daypicker): Add markup and styles to display price information

- src/components/DayPicker/__tests__/Day.spec.js
- src/components/DayPicker/__tests__/DayPicker.spec.js
- src/components/DayPicker/__tests__/Header.spec.js
- src/components/DayPicker/__tests__/Month.spec.js
- src/components/DayPicker/__tests__/Price.spec.js
- src/components/DayPicker/__tests__/Tabs.spec.js
- src/components/DayPicker/__tests__/__snapshots__/Day.spec.js.snap
- src/components/DayPicker/__tests__/__snapshots__/DayPicker.spec.js.snap
- src/components/DayPicker/__tests__/__snapshots__/Month.spec.js.snap
- src/components/DayPicker/__tests__/__snapshots__/Price.spec.js.snap
- src/components/DayPicker/__tests__/__snapshots__/Tabs.spec.js.snap
- src/components/DayPicker/components/Day.js
- src/components/DayPicker/components/Month.js
- src/components/DayPicker/index.js
- src/components/PopupField/__tests__/__snapshots__/PopupField.spec.js.snap
- src/components/PopupField/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/52)
> feat(daypicker): Add missing tests and minor bugfixes

- rollup.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/72)
> fix(theme): Remove explicit theme export from index write

- src/components/NumericInput/README.md
- src/components/NumericInput/__tests__/NumericInput.spec.js
- src/components/NumericInput/__tests__/__snapshots__/NumericInput.spec.js.snap
- src/components/NumericInput/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/82)
> fix(passengers): To prevent keyboard pop up in mobiles when up/down keys pressed

- src/components/DayPicker/__tests__/DayPicker.spec.js
- src/components/DayPicker/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/84)
> fix(DayPicker): CONSIDER-1079 Bug fix - Partial return date selection issue

- src/shared/ButtonWithDialog/components/Dialog.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/88)
> fix(daypicker): Fix scrollTarget proptype

- commitlint.config.js
- package-lock.json
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/93)
> feat(commitlint): added commitlint with angular configuration

- src/components/Typeahead/__tests__/__snapshots__/Typeahead.spec.js.snap
- src/components/Typeahead/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/98)
> fix(typeahead): add bottom padding for the list to fix the scroll issue

- README.md
- styleguide.config.js
You can preview this here:
https://github.com/qantasairways/runway/tree/feature/readme-improvements
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/101)
> feat(readme): added contributing guidelines

- src/components/DayPicker/README.md
- src/components/DayPicker/helpers/index.js
- src/components/DayPicker/index.js
- src/components/DisclaimerMessages/README.md
- src/components/DisclaimerMessages/__tests__/DisclaimerMessages.spec.js
- src/components/DisclaimerMessages/__tests__/__snapshots__/DisclaimerMessages.spec.js.snap
- src/components/DisclaimerMessages/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/104)
> feat(DayPicker): To display Disclaimer message

- src/components/DisclaimerMessages/__tests__/__snapshots__/DisclaimerMessages.spec.js.snap
- src/components/DisclaimerMessages/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/110)
> feat(daypicker): bug fix and enhancement

- src/components/DayPicker/__tests__/DayPicker.spec.js
- src/components/DayPicker/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/111)
> fix(daypicker): include logic when startDate is already set

- src/components/DayPicker/__tests__/DayPicker.spec.js
- src/components/DayPicker/helpers/index.js
- src/components/DayPicker/index.js
- src/components/DisclaimerMessages/__tests__/__snapshots__/DisclaimerMessages.spec.js.snap
- src/components/DisclaimerMessages/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/112)
> feat(daypicker): code enhancement for disclaimer message

- src/components/DayPicker/components/Footer.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/118)
> fix(daypicker): change the argument to show the prefooter disclaimer

- src/components/Dropdown/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/126)
> fix(dropdown): do not select item onBlur

- src/components/Dropdown/README.md
- src/components/Dropdown/__tests__/Dropdown.spec.js
- src/components/Dropdown/__tests__/__snapshots__/Dropdown.spec.js.snap
- src/components/Dropdown/components/Menu.js
- src/components/Dropdown/components/MenuItem.js
- src/components/Dropdown/index.js
…erline the selected item
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/125)
> feat(dropdown): Add props for height of dropdown and highlighted, inline and growMenu variation

- rollup.js
Related to https://github.com/qantasairways/runway/pull/127
I think this could potentially improve efficiency, only open and write the file once.  😄
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/130)
> feat(rollup):Only open the file once and write to the file

- CONTRIBUTING.md
- package-lock.json
- package.json
- rollup.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/127)
> feat(npmlink): watch for changes with install npm watch package

- src/components/Dropdown/__tests__/__snapshots__/Dropdown.spec.js.snap
- src/components/Dropdown/components/MenuItem.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/129)
> fix(dropdown, menuitem): arrow keys highlight on focus 

- src/components/Toggle/__tests__/Toggle.spec.js
- src/components/Toggle/__tests__/__snapshots__/Toggle.spec.js.snap
- src/components/Toggle/index.js
- Removed swapPosition prop and logic
- Made some props non-mandatory (id, onChange, checked, spaceBetween, handleSize, height and width)
- Show background for all viewports
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/131)
> fix(toggle): Minor issues fixed for toggle component

- src/components/Dropdown/__tests__/__snapshots__/Dropdown.spec.js.snap
- src/components/Dropdown/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/132)
> fix(dropdown): dropdown should not open on focus

- src/components/Toggle/README.md
- src/components/Toggle/__tests__/__snapshots__/Toggle.spec.js.snap
- src/components/Toggle/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/135)
> feat(toggle): clean up and simplify the toggle component

- package-lock.json
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/139)
> feat(setup): remove unused libraries

- src/components/NumericInput/__tests__/__snapshots__/NumericInput.spec.js.snap
- src/components/NumericInput/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/141)
> fix(numericinput): fix the plus icon in ie

- .gitignore
- package-lock.json
- src/components/Dropdown/__tests__/__snapshots__/Dropdown.spec.js.snap
- src/components/Dropdown/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/146)
> fix(dropdown): fix dropdown to selectable all box

- .gitignore
- src/components/Dropdown/__tests__/__snapshots__/Dropdown.spec.js.snap
- src/components/Dropdown/index.js
This reverts commit 3d7ce1a414da4d687d6700c15c6ae06ecca3cbaf.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/147)
> Revert "fix(dropdown): fix dropdown to selectable all box (#146)"

- package-lock.json
- src/components/PopupField/__tests__/__snapshots__/PopupField.spec.js.snap
- src/shared/ButtonWithDialog/__test__/__snapshots__/Button.spec.js.snap
- src/shared/ButtonWithDialog/__test__/__snapshots__/ButtonWithDialog.spec.js.snap
- src/shared/ButtonWithDialog/components/Button.js
- src/theme/airways/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/140)
> feat(button): changed the height and font size of the button

- package-lock.json
- src/icons/CalendarIcon/__tests__/CalendarIcon.spec.js
- src/icons/CalendarIcon/__tests__/__snapshots__/CalendarIcon.spec.js.snap
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/150)
> fix(calendaricon): added comprehensive unit tests

- src/icons/ChevronDown/__tests__/ChevronDown.spec.js
- src/icons/ChevronDown/__tests__/__snapshots__/ChevronDown.spec.js.snap
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/151)
> fix(chevron-down-icon): added comprehensive unit tests

- src/icons/MinusIcon/__tests__/MinusIcon.spec.js
- src/icons/MinusIcon/__tests__/__snapshots__/MinusIcon.spec.js.snap
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/156)
> fix(minus-icon): added comprehensive unit tests

- src/components/PopupField/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/163)
> fix(popup-field): ios safari does not scroll in the typeahead

- .gitignore
- src/components/Dropdown/__tests__/__snapshots__/Dropdown.spec.js.snap
- src/components/Dropdown/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/160)
> fix(dropdown): fix dropdown to be selectable all box

- .circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/166)
> fix(circleci): upgrade to node v8.16 to fix semantic versioning

- src/components/FocusLock/index.js
- src/components/Typeahead/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/167)
> fix(typeahead): fix scroll ref

- src/components/FocusLock/index.js
- src/components/Typeahead/index.js
This reverts commit 9156a05bdb09b9e8cc74de9df9fee27ec2a6b440.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/170)
> Revert "fix(typeahead): fix scroll ref (#167)"

- package-lock.json
- src/components/Button/__tests__/__snapshots__/Button.spec.js.snap
- src/components/PopupField/__tests__/__snapshots__/Footer.spec.js.snap
- src/theme/airways/colours.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/181)
> fix(theme): change the red color

- src/components/MenuItem/__tests__/__snapshots__/MenuItem.spec.js.snap
- src/components/Select/__tests__/__snapshots__/Select.spec.js.snap
- src/icons/ChevronDown/__tests__/__snapshots__/ChevronDown.spec.js.snap
- src/icons/ChevronDown/index.js
- src/icons/MinusIcon/__tests__/__snapshots__/MinusIcon.spec.js.snap
- src/icons/MinusIcon/index.js
- src/icons/PlusIcon/index.js
- src/icons/Tick/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/180)
> fix(icons): add focusable false to icons for ie11

- src/components/FocusLock/index.js
Focus Traps have been added for cases where the focus lock element is rendered at the beginning or end of the DOM. If `[TAB]` key is pressed when the currently focused element is the last focusable element in the DOM tree, the browser will focus outside the document and not fire the `focusin` event listener. To fix this I've added some focus traps surrounding the focus lock container, these traps have `tab-index="0"` to force a focusable state, if one of these is focused, the focus will be reset to inside the locked area.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qantasairways/runway/184)
> feat(focuslock): add focus traps
